{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-crdt" (include "resume-builder.fullname" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resume-builder.fullname" . }}-crdt
  labels:
    {{- include "resume-builder.labels" . | nindent 4 }}
    app.kubernetes.io/component: crdt
type: Opaque
{{- if and $existingSecret (not .Values.crdt.internalKey) }}
data:
  internalKey: {{ index $existingSecret.data "internalKey" }}
{{- else }}
stringData:
  internalKey: {{ .Values.crdt.internalKey | default (randAlphaNum 32) | quote }}
{{- end }}
