{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-password" .Values.mongodb.name) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.name }}-password
type: Opaque
{{- if and $existingSecret (not .Values.mongodb.password) }}
data:
  password: {{ index $existingSecret.data "password" }}
{{- else }}
stringData:
  password: {{ .Values.mongodb.password | default (randAlphaNum 32) | quote }}
{{- end }}
