apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.mongodb.name }}-password
type: Opaque
stringData:
  password: {{ .Values.mongodb.password | default (randAlphaNum 32) | quote }}
{{- if not (lookup "v1" "Secret" .Release.Namespace (printf "%s-password" .Values.mongodb.name)) }}
  # Generated on first install; will not be overwritten on upgrade
{{- end }}
