apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: {{ include "resume-builder.fullname" . }}-postgres
  labels:
    {{- include "resume-builder.labels" . | nindent 4 }}
spec:
  instances: {{ .Values.postgres.instances }}
  bootstrap:
    initdb:
      database: {{ .Values.postgres.database }}
      owner: {{ .Values.postgres.username }}
      postInitApplicationSQL:
        - CREATE EXTENSION IF NOT EXISTS vector;
      secret:
        name: {{ include "resume-builder.fullname" . }}-postgres-user
  storage:
    size: {{ .Values.postgres.storage }}
