{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (printf "%s-postgres-user" (include "resume-builder.fullname" .)) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resume-builder.fullname" . }}-postgres-user
  labels:
    {{- include "resume-builder.labels" . | nindent 4 }}
type: kubernetes.io/basic-auth
{{- if and $existingSecret (not .Values.postgres.password) }}
data:
  username: {{ index $existingSecret.data "username" }}
  password: {{ index $existingSecret.data "password" }}
{{- else }}
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | default (randAlphaNum 32) | quote }}
{{- end }}
