{{- $existingSecret := lookup "v1" "Secret" .Release.Namespace (include "resume-builder.redis.fullname" .) -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "resume-builder.redis.fullname" . }}
  labels:
    {{- include "resume-builder.labels" . | nindent 4 }}
type: Opaque
{{- if and $existingSecret (not .Values.redis.password) }}
data:
  password: {{ index $existingSecret.data "password" }}
{{- else }}
stringData:
  password: {{ .Values.redis.password | default (randAlphaNum 32) | quote }}
{{- end }}
