apiVersion: v1
kind: Service
metadata:
  name: {{ include "resume-builder.redis.fullname" . }}
  labels:
    {{- include "resume-builder.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.redis.port }}
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "resume-builder.redis.selectorLabels" . | nindent 4 }}
