apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "resume-builder.redis.fullname" . }}
  labels:
    {{- include "resume-builder.labels" . | nindent 4 }}
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.redis.storage }}
