/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PreviewRouteImport } from './routes/preview'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as IndexRouteImport } from './routes/index'
import { Route as EditorIndexRouteImport } from './routes/editor/index'
import { Route as EditorResumeIdRouteImport } from './routes/editor/$resumeId'
import { Route as EditorLocalFilenameRouteImport } from './routes/editor/local/$filename'

const PreviewRoute = PreviewRouteImport.update({
  id: '/preview',
  path: '/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorIndexRoute = EditorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EditorRoute,
} as any)
const EditorResumeIdRoute = EditorResumeIdRouteImport.update({
  id: '/$resumeId',
  path: '/$resumeId',
  getParentRoute: () => EditorRoute,
} as any)
const EditorLocalFilenameRoute = EditorLocalFilenameRouteImport.update({
  id: '/local/$filename',
  path: '/local/$filename',
  getParentRoute: () => EditorRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteWithChildren
  '/preview': typeof PreviewRoute
  '/editor/$resumeId': typeof EditorResumeIdRoute
  '/editor/': typeof EditorIndexRoute
  '/editor/local/$filename': typeof EditorLocalFilenameRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/preview': typeof PreviewRoute
  '/editor/$resumeId': typeof EditorResumeIdRoute
  '/editor': typeof EditorIndexRoute
  '/editor/local/$filename': typeof EditorLocalFilenameRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/editor': typeof EditorRouteWithChildren
  '/preview': typeof PreviewRoute
  '/editor/$resumeId': typeof EditorResumeIdRoute
  '/editor/': typeof EditorIndexRoute
  '/editor/local/$filename': typeof EditorLocalFilenameRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/editor'
    | '/preview'
    | '/editor/$resumeId'
    | '/editor/'
    | '/editor/local/$filename'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/preview'
    | '/editor/$resumeId'
    | '/editor'
    | '/editor/local/$filename'
  id:
    | '__root__'
    | '/'
    | '/editor'
    | '/preview'
    | '/editor/$resumeId'
    | '/editor/'
    | '/editor/local/$filename'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  EditorRoute: typeof EditorRouteWithChildren
  PreviewRoute: typeof PreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/preview': {
      id: '/preview'
      path: '/preview'
      fullPath: '/preview'
      preLoaderRoute: typeof PreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor/': {
      id: '/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof EditorIndexRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/$resumeId': {
      id: '/editor/$resumeId'
      path: '/$resumeId'
      fullPath: '/editor/$resumeId'
      preLoaderRoute: typeof EditorResumeIdRouteImport
      parentRoute: typeof EditorRoute
    }
    '/editor/local/$filename': {
      id: '/editor/local/$filename'
      path: '/local/$filename'
      fullPath: '/editor/local/$filename'
      preLoaderRoute: typeof EditorLocalFilenameRouteImport
      parentRoute: typeof EditorRoute
    }
  }
}

interface EditorRouteChildren {
  EditorResumeIdRoute: typeof EditorResumeIdRoute
  EditorIndexRoute: typeof EditorIndexRoute
  EditorLocalFilenameRoute: typeof EditorLocalFilenameRoute
}

const EditorRouteChildren: EditorRouteChildren = {
  EditorResumeIdRoute: EditorResumeIdRoute,
  EditorIndexRoute: EditorIndexRoute,
  EditorLocalFilenameRoute: EditorLocalFilenameRoute,
}

const EditorRouteWithChildren =
  EditorRoute._addFileChildren(EditorRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  EditorRoute: EditorRouteWithChildren,
  PreviewRoute: PreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
