/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PublicRouteImport } from './routes/_public'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFeedbackRouteImport } from './routes/_authenticated/feedback'
import { Route as AuthenticatedEditorRouteImport } from './routes/_authenticated/editor'
import { Route as publicLogoutRouteImport } from './routes/(public)/logout'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as AuthenticatedProfileIndexRouteImport } from './routes/_authenticated/profile/index'
import { Route as AuthenticatedEditorIndexRouteImport } from './routes/_authenticated/editor/index'
import { Route as AuthenticatedProfileWorkHistoryRouteImport } from './routes/_authenticated/profile/work-history'
import { Route as AuthenticatedProfileVolunteeringRouteImport } from './routes/_authenticated/profile/volunteering'
import { Route as AuthenticatedProfileStatementsRouteImport } from './routes/_authenticated/profile/statements'
import { Route as AuthenticatedProfileSkillsRouteImport } from './routes/_authenticated/profile/skills'
import { Route as AuthenticatedProfileProjectsRouteImport } from './routes/_authenticated/profile/projects'
import { Route as AuthenticatedProfilePreferencesRouteImport } from './routes/_authenticated/profile/preferences'
import { Route as AuthenticatedProfileFactsRouteImport } from './routes/_authenticated/profile/facts'
import { Route as AuthenticatedProfileConceptsRouteImport } from './routes/_authenticated/profile/concepts'
import { Route as AuthenticatedProfileBackgroundRouteImport } from './routes/_authenticated/profile/background'
import { Route as AuthenticatedPreviewApplicationIdRouteImport } from './routes/_authenticated/preview.$applicationId'
import { Route as AuthenticatedExportApplicationIdRouteImport } from './routes/_authenticated/export.$applicationId'
import { Route as AuthenticatedEditorApplicationIdRouteImport } from './routes/_authenticated/editor/$applicationId'
import { Route as AuthenticatedApplicationsApplicationIdRouteImport } from './routes/_authenticated/applications.$applicationId'

const PublicRoute = PublicRouteImport.update({
  id: '/_public',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedFeedbackRoute = AuthenticatedFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedEditorRoute = AuthenticatedEditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const publicLogoutRoute = publicLogoutRouteImport.update({
  id: '/(public)/logout',
  path: '/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileIndexRoute =
  AuthenticatedProfileIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedEditorIndexRoute =
  AuthenticatedEditorIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedEditorRoute,
  } as any)
const AuthenticatedProfileWorkHistoryRoute =
  AuthenticatedProfileWorkHistoryRouteImport.update({
    id: '/work-history',
    path: '/work-history',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileVolunteeringRoute =
  AuthenticatedProfileVolunteeringRouteImport.update({
    id: '/volunteering',
    path: '/volunteering',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileStatementsRoute =
  AuthenticatedProfileStatementsRouteImport.update({
    id: '/statements',
    path: '/statements',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileSkillsRoute =
  AuthenticatedProfileSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileProjectsRoute =
  AuthenticatedProfileProjectsRouteImport.update({
    id: '/projects',
    path: '/projects',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfilePreferencesRoute =
  AuthenticatedProfilePreferencesRouteImport.update({
    id: '/preferences',
    path: '/preferences',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileFactsRoute =
  AuthenticatedProfileFactsRouteImport.update({
    id: '/facts',
    path: '/facts',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileConceptsRoute =
  AuthenticatedProfileConceptsRouteImport.update({
    id: '/concepts',
    path: '/concepts',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedProfileBackgroundRoute =
  AuthenticatedProfileBackgroundRouteImport.update({
    id: '/background',
    path: '/background',
    getParentRoute: () => AuthenticatedProfileRoute,
  } as any)
const AuthenticatedPreviewApplicationIdRoute =
  AuthenticatedPreviewApplicationIdRouteImport.update({
    id: '/preview/$applicationId',
    path: '/preview/$applicationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExportApplicationIdRoute =
  AuthenticatedExportApplicationIdRouteImport.update({
    id: '/export/$applicationId',
    path: '/export/$applicationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedEditorApplicationIdRoute =
  AuthenticatedEditorApplicationIdRouteImport.update({
    id: '/$applicationId',
    path: '/$applicationId',
    getParentRoute: () => AuthenticatedEditorRoute,
  } as any)
const AuthenticatedApplicationsApplicationIdRoute =
  AuthenticatedApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/login': typeof publicLoginRoute
  '/logout': typeof publicLogoutRoute
  '/editor': typeof AuthenticatedEditorRouteWithChildren
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/home': typeof AuthenticatedHomeRoute
  '/profile': typeof AuthenticatedProfileRouteWithChildren
  '/': typeof AuthenticatedIndexRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/editor/$applicationId': typeof AuthenticatedEditorApplicationIdRoute
  '/export/$applicationId': typeof AuthenticatedExportApplicationIdRoute
  '/preview/$applicationId': typeof AuthenticatedPreviewApplicationIdRoute
  '/profile/background': typeof AuthenticatedProfileBackgroundRoute
  '/profile/concepts': typeof AuthenticatedProfileConceptsRoute
  '/profile/facts': typeof AuthenticatedProfileFactsRoute
  '/profile/preferences': typeof AuthenticatedProfilePreferencesRoute
  '/profile/projects': typeof AuthenticatedProfileProjectsRoute
  '/profile/skills': typeof AuthenticatedProfileSkillsRoute
  '/profile/statements': typeof AuthenticatedProfileStatementsRoute
  '/profile/volunteering': typeof AuthenticatedProfileVolunteeringRoute
  '/profile/work-history': typeof AuthenticatedProfileWorkHistoryRoute
  '/editor/': typeof AuthenticatedEditorIndexRoute
  '/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof publicLoginRoute
  '/logout': typeof publicLogoutRoute
  '/feedback': typeof AuthenticatedFeedbackRoute
  '/home': typeof AuthenticatedHomeRoute
  '/': typeof AuthenticatedIndexRoute
  '/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/editor/$applicationId': typeof AuthenticatedEditorApplicationIdRoute
  '/export/$applicationId': typeof AuthenticatedExportApplicationIdRoute
  '/preview/$applicationId': typeof AuthenticatedPreviewApplicationIdRoute
  '/profile/background': typeof AuthenticatedProfileBackgroundRoute
  '/profile/concepts': typeof AuthenticatedProfileConceptsRoute
  '/profile/facts': typeof AuthenticatedProfileFactsRoute
  '/profile/preferences': typeof AuthenticatedProfilePreferencesRoute
  '/profile/projects': typeof AuthenticatedProfileProjectsRoute
  '/profile/skills': typeof AuthenticatedProfileSkillsRoute
  '/profile/statements': typeof AuthenticatedProfileStatementsRoute
  '/profile/volunteering': typeof AuthenticatedProfileVolunteeringRoute
  '/profile/work-history': typeof AuthenticatedProfileWorkHistoryRoute
  '/editor': typeof AuthenticatedEditorIndexRoute
  '/profile': typeof AuthenticatedProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/_public': typeof PublicRoute
  '/(public)/login': typeof publicLoginRoute
  '/(public)/logout': typeof publicLogoutRoute
  '/_authenticated/editor': typeof AuthenticatedEditorRouteWithChildren
  '/_authenticated/feedback': typeof AuthenticatedFeedbackRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRouteWithChildren
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/applications/$applicationId': typeof AuthenticatedApplicationsApplicationIdRoute
  '/_authenticated/editor/$applicationId': typeof AuthenticatedEditorApplicationIdRoute
  '/_authenticated/export/$applicationId': typeof AuthenticatedExportApplicationIdRoute
  '/_authenticated/preview/$applicationId': typeof AuthenticatedPreviewApplicationIdRoute
  '/_authenticated/profile/background': typeof AuthenticatedProfileBackgroundRoute
  '/_authenticated/profile/concepts': typeof AuthenticatedProfileConceptsRoute
  '/_authenticated/profile/facts': typeof AuthenticatedProfileFactsRoute
  '/_authenticated/profile/preferences': typeof AuthenticatedProfilePreferencesRoute
  '/_authenticated/profile/projects': typeof AuthenticatedProfileProjectsRoute
  '/_authenticated/profile/skills': typeof AuthenticatedProfileSkillsRoute
  '/_authenticated/profile/statements': typeof AuthenticatedProfileStatementsRoute
  '/_authenticated/profile/volunteering': typeof AuthenticatedProfileVolunteeringRoute
  '/_authenticated/profile/work-history': typeof AuthenticatedProfileWorkHistoryRoute
  '/_authenticated/editor/': typeof AuthenticatedEditorIndexRoute
  '/_authenticated/profile/': typeof AuthenticatedProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/logout'
    | '/editor'
    | '/feedback'
    | '/home'
    | '/profile'
    | '/'
    | '/applications/$applicationId'
    | '/editor/$applicationId'
    | '/export/$applicationId'
    | '/preview/$applicationId'
    | '/profile/background'
    | '/profile/concepts'
    | '/profile/facts'
    | '/profile/preferences'
    | '/profile/projects'
    | '/profile/skills'
    | '/profile/statements'
    | '/profile/volunteering'
    | '/profile/work-history'
    | '/editor/'
    | '/profile/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/logout'
    | '/feedback'
    | '/home'
    | '/'
    | '/applications/$applicationId'
    | '/editor/$applicationId'
    | '/export/$applicationId'
    | '/preview/$applicationId'
    | '/profile/background'
    | '/profile/concepts'
    | '/profile/facts'
    | '/profile/preferences'
    | '/profile/projects'
    | '/profile/skills'
    | '/profile/statements'
    | '/profile/volunteering'
    | '/profile/work-history'
    | '/editor'
    | '/profile'
  id:
    | '__root__'
    | '/_authenticated'
    | '/_public'
    | '/(public)/login'
    | '/(public)/logout'
    | '/_authenticated/editor'
    | '/_authenticated/feedback'
    | '/_authenticated/home'
    | '/_authenticated/profile'
    | '/_authenticated/'
    | '/_authenticated/applications/$applicationId'
    | '/_authenticated/editor/$applicationId'
    | '/_authenticated/export/$applicationId'
    | '/_authenticated/preview/$applicationId'
    | '/_authenticated/profile/background'
    | '/_authenticated/profile/concepts'
    | '/_authenticated/profile/facts'
    | '/_authenticated/profile/preferences'
    | '/_authenticated/profile/projects'
    | '/_authenticated/profile/skills'
    | '/_authenticated/profile/statements'
    | '/_authenticated/profile/volunteering'
    | '/_authenticated/profile/work-history'
    | '/_authenticated/editor/'
    | '/_authenticated/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  PublicRoute: typeof PublicRoute
  publicLoginRoute: typeof publicLoginRoute
  publicLogoutRoute: typeof publicLogoutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_public': {
      id: '/_public'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof PublicRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feedback': {
      id: '/_authenticated/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof AuthenticatedFeedbackRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editor': {
      id: '/_authenticated/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof AuthenticatedEditorRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/(public)/logout': {
      id: '/(public)/logout'
      path: '/logout'
      fullPath: '/logout'
      preLoaderRoute: typeof publicLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile/': {
      id: '/_authenticated/profile/'
      path: '/'
      fullPath: '/profile/'
      preLoaderRoute: typeof AuthenticatedProfileIndexRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/editor/': {
      id: '/_authenticated/editor/'
      path: '/'
      fullPath: '/editor/'
      preLoaderRoute: typeof AuthenticatedEditorIndexRouteImport
      parentRoute: typeof AuthenticatedEditorRoute
    }
    '/_authenticated/profile/work-history': {
      id: '/_authenticated/profile/work-history'
      path: '/work-history'
      fullPath: '/profile/work-history'
      preLoaderRoute: typeof AuthenticatedProfileWorkHistoryRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/volunteering': {
      id: '/_authenticated/profile/volunteering'
      path: '/volunteering'
      fullPath: '/profile/volunteering'
      preLoaderRoute: typeof AuthenticatedProfileVolunteeringRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/statements': {
      id: '/_authenticated/profile/statements'
      path: '/statements'
      fullPath: '/profile/statements'
      preLoaderRoute: typeof AuthenticatedProfileStatementsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/skills': {
      id: '/_authenticated/profile/skills'
      path: '/skills'
      fullPath: '/profile/skills'
      preLoaderRoute: typeof AuthenticatedProfileSkillsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/projects': {
      id: '/_authenticated/profile/projects'
      path: '/projects'
      fullPath: '/profile/projects'
      preLoaderRoute: typeof AuthenticatedProfileProjectsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/preferences': {
      id: '/_authenticated/profile/preferences'
      path: '/preferences'
      fullPath: '/profile/preferences'
      preLoaderRoute: typeof AuthenticatedProfilePreferencesRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/facts': {
      id: '/_authenticated/profile/facts'
      path: '/facts'
      fullPath: '/profile/facts'
      preLoaderRoute: typeof AuthenticatedProfileFactsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/concepts': {
      id: '/_authenticated/profile/concepts'
      path: '/concepts'
      fullPath: '/profile/concepts'
      preLoaderRoute: typeof AuthenticatedProfileConceptsRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/profile/background': {
      id: '/_authenticated/profile/background'
      path: '/background'
      fullPath: '/profile/background'
      preLoaderRoute: typeof AuthenticatedProfileBackgroundRouteImport
      parentRoute: typeof AuthenticatedProfileRoute
    }
    '/_authenticated/preview/$applicationId': {
      id: '/_authenticated/preview/$applicationId'
      path: '/preview/$applicationId'
      fullPath: '/preview/$applicationId'
      preLoaderRoute: typeof AuthenticatedPreviewApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/export/$applicationId': {
      id: '/_authenticated/export/$applicationId'
      path: '/export/$applicationId'
      fullPath: '/export/$applicationId'
      preLoaderRoute: typeof AuthenticatedExportApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/editor/$applicationId': {
      id: '/_authenticated/editor/$applicationId'
      path: '/$applicationId'
      fullPath: '/editor/$applicationId'
      preLoaderRoute: typeof AuthenticatedEditorApplicationIdRouteImport
      parentRoute: typeof AuthenticatedEditorRoute
    }
    '/_authenticated/applications/$applicationId': {
      id: '/_authenticated/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthenticatedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedEditorRouteChildren {
  AuthenticatedEditorApplicationIdRoute: typeof AuthenticatedEditorApplicationIdRoute
  AuthenticatedEditorIndexRoute: typeof AuthenticatedEditorIndexRoute
}

const AuthenticatedEditorRouteChildren: AuthenticatedEditorRouteChildren = {
  AuthenticatedEditorApplicationIdRoute: AuthenticatedEditorApplicationIdRoute,
  AuthenticatedEditorIndexRoute: AuthenticatedEditorIndexRoute,
}

const AuthenticatedEditorRouteWithChildren =
  AuthenticatedEditorRoute._addFileChildren(AuthenticatedEditorRouteChildren)

interface AuthenticatedProfileRouteChildren {
  AuthenticatedProfileBackgroundRoute: typeof AuthenticatedProfileBackgroundRoute
  AuthenticatedProfileConceptsRoute: typeof AuthenticatedProfileConceptsRoute
  AuthenticatedProfileFactsRoute: typeof AuthenticatedProfileFactsRoute
  AuthenticatedProfilePreferencesRoute: typeof AuthenticatedProfilePreferencesRoute
  AuthenticatedProfileProjectsRoute: typeof AuthenticatedProfileProjectsRoute
  AuthenticatedProfileSkillsRoute: typeof AuthenticatedProfileSkillsRoute
  AuthenticatedProfileStatementsRoute: typeof AuthenticatedProfileStatementsRoute
  AuthenticatedProfileVolunteeringRoute: typeof AuthenticatedProfileVolunteeringRoute
  AuthenticatedProfileWorkHistoryRoute: typeof AuthenticatedProfileWorkHistoryRoute
  AuthenticatedProfileIndexRoute: typeof AuthenticatedProfileIndexRoute
}

const AuthenticatedProfileRouteChildren: AuthenticatedProfileRouteChildren = {
  AuthenticatedProfileBackgroundRoute: AuthenticatedProfileBackgroundRoute,
  AuthenticatedProfileConceptsRoute: AuthenticatedProfileConceptsRoute,
  AuthenticatedProfileFactsRoute: AuthenticatedProfileFactsRoute,
  AuthenticatedProfilePreferencesRoute: AuthenticatedProfilePreferencesRoute,
  AuthenticatedProfileProjectsRoute: AuthenticatedProfileProjectsRoute,
  AuthenticatedProfileSkillsRoute: AuthenticatedProfileSkillsRoute,
  AuthenticatedProfileStatementsRoute: AuthenticatedProfileStatementsRoute,
  AuthenticatedProfileVolunteeringRoute: AuthenticatedProfileVolunteeringRoute,
  AuthenticatedProfileWorkHistoryRoute: AuthenticatedProfileWorkHistoryRoute,
  AuthenticatedProfileIndexRoute: AuthenticatedProfileIndexRoute,
}

const AuthenticatedProfileRouteWithChildren =
  AuthenticatedProfileRoute._addFileChildren(AuthenticatedProfileRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedEditorRoute: typeof AuthenticatedEditorRouteWithChildren
  AuthenticatedFeedbackRoute: typeof AuthenticatedFeedbackRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRouteWithChildren
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedApplicationsApplicationIdRoute: typeof AuthenticatedApplicationsApplicationIdRoute
  AuthenticatedExportApplicationIdRoute: typeof AuthenticatedExportApplicationIdRoute
  AuthenticatedPreviewApplicationIdRoute: typeof AuthenticatedPreviewApplicationIdRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedEditorRoute: AuthenticatedEditorRouteWithChildren,
  AuthenticatedFeedbackRoute: AuthenticatedFeedbackRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRouteWithChildren,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedApplicationsApplicationIdRoute:
    AuthenticatedApplicationsApplicationIdRoute,
  AuthenticatedExportApplicationIdRoute: AuthenticatedExportApplicationIdRoute,
  AuthenticatedPreviewApplicationIdRoute:
    AuthenticatedPreviewApplicationIdRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  PublicRoute: PublicRoute,
  publicLoginRoute: publicLoginRoute,
  publicLogoutRoute: publicLogoutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
